[package]

name = "rsedis"
version = "0.0.1"
authors = [ "Sebastian Waisbrot <seppo0010@gmail.com>" ]
exclude = [
    ".gitignore",
    ".travis.yml",
    "tests/*",
]

[[bin]]

name = "rsedis"

[[test]]

name = "tests"
path = "tests/tests.rs"

[dependencies.config]
path = "config"

[dependencies]
time = "0.1"
rand = "0.3.8"
skiplist = "0.2.4"

[target.x86_64-unknown-linux-gnu.dependencies]
libc ="0.1.8"

[target.x86_64-apple-darwin.dependencies]
libc ="0.1.8"
