[package]
name = "database"
version = "0.1.0"
authors = ["Sebastian Waisbrot <seppo0010@gmail.com>"]

[dependencies.config]
path = "../config"

# TODO: publish the repository in crates.io
# Do not forget to do that before pushing
[dependencies.crc64]
path = "../../crc64"

[dependencies.logger]
path = "../logger"

[dependencies.util]
path = "../util"

[dependencies.rdbutil]
path = "./rdbutil"

[dependencies.response]
path = "../response"

[dependencies]
rand = "0.3.8"
skiplist = "0.2.6"
rehashinghashmap = "0.1.0"
